# Generated by Django 5.1.1 on 2024-09-27 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('in progress', 'В работе'), ('done', 'Исполнено'), ('cancelled', 'Отменено'), ('delayed start', 'Отложить начало'), ('wait for start', 'Ожидает начала')], default='wait for start', max_length=30)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
